/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


float
calculadora_prog_1(char *host, float a, float b, float c, float d,char op, CLIENT *clnt)
{
	float  *result_1;
	inputs  add_1_arg;
	float  *result_2;
	inputs  sub_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;
	float  *result_5;
	inputs  pot_1_arg;

//SUMA
if(op=='+'){

	add_1_arg.num1=a;
	add_1_arg.num2=b;
	add_1_arg.num3=c;
	add_1_arg.num4=d;
	add_1_arg.operador=op;
	
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_1;
}

//RESTA
if(op=='-'){

	sub_1_arg.num1=a;
	sub_1_arg.num2=b;
	sub_1_arg.num3=c;
	sub_1_arg.num4=d;
	sub_1_arg.operador=op;

	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_2;
}
	
//MULTIPLICACION
if(op=='*'){

	mul_1_arg.num1=a;
	mul_1_arg.num2=b;
	mul_1_arg.num3=c;
	mul_1_arg.num4=d;
	mul_1_arg.operador=op;
	
	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_3;
}
	
//DIVISION
if(op=='/'){

	div_1_arg.num1=a;
	div_1_arg.num2=b;
	div_1_arg.num3=c;
	div_1_arg.num4=d;
	div_1_arg.operador=op;

	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_4;
}
	
}


int
main (int argc, char *argv[])
{
	//Añadimos las variables que faltan
	char *host;
	float a, b, c, d;
	char op;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	//Creamos un pequeño menu
	printf("Bienvenido estas usando la calculadora de Claudia \n");
	printf("Recuerda: \n + para la SUMA \n - para la RESTA \n * para la multiplicacion \n / para la division \n");
	printf("Indique el numerador de la primera fraccion \n");
	scanf("%f", &a);
	printf("Indique el denominador de la primera fraccion \n");
	scanf("%f", &b);
	printf("Indique el numerador de la segunda fraccion \n");
	scanf("%f", &c);
	printf("Indique el denominador de la segunda fraccion \n");
	scanf("%f", &d);
	printf("Indique el operador \n");
	scanf("%s", &op);
	
	//Viene por defecto al crearse con rpcgen, lo dejo asi.
	host = argv[1];
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
	//Imprimimos el resultado
	printf("El resultado es: %f \n",calculadora_prog_1(host,a,b,c,d,op,clnt));
	
	//Viene por defecto al crearse con rpcgen, lo dejo asi.
	clnt_destroy (clnt);
	exit (0);
}
