/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

//Creonun metodo que haga el MCD que  nos sirve para sacar el MCM
float maximo_comun_divisor(float a, float b) {
   float temporal;//Para no perder b
   float aux;
    while (b != 0) {
        temporal = b;
        aux=a/b;
        b = a-(aux*b);
        a = temporal;
    }
    return a;
}

//Hago este metodo del MCM para que sea mas sencillo hacer la suma y la resta
float minimo_comun_multiplo(float a, float b) {
    return (a * b) / maximo_comun_divisor(a, b);
}


//SUMA
float *add_1_svc(inputs *argp, struct svc_req *rqstp){
	static float  result;
	
	//Todo lo necesario para sumar fracciones
	float mcm=minimo_comun_multiplo(argp->num2,argp->num4);	//Calcula el mcm de los denominadores
	float m1=mcm/argp->num2*argp->num1;				//Calcula el numerador de la primera fraccion
	float m2=mcm/argp->num4*argp->num3;				//Calcula el numerador de la segunda fraccion
	float m=m1+m2;							//Calcula el numerador total
	
	//Ponemos aqui nuestro codigo para la suma
	result = m/mcm;
	printf("Got Request : Suma %f/%f y %f/%f \n",argp->num1,argp->num2,argp->num3,argp->num4);
	printf("Sent Response : %f/%f = %f \n",m,mcm,result);

	return &result;
}


//RESTA
float *sub_1_svc(inputs *argp, struct svc_req *rqstp){
	static float  result;
	
	//Todo lo necesario para la resta de Fracciones
	float mcm=minimo_comun_multiplo(argp->num2,argp->num4); 	//Calcula el mcm de los denominadores
	float m1=mcm/argp->num2*argp->num1;				//Calcula el numerador de la primera fraccion
	float m2=mcm/argp->num4*argp->num3;				//Calcula el numerador de la segunda fraccion
	float m=m1-m2;							//Calcula el numerador total
	

	//Ponemos aqui nuestro codigo para la resta
	result = m/mcm;
	printf("Got Request : Resta %f/%f y %f/%f \n",argp->num1,argp->num2,argp->num3,argp->num4);
	printf("Sent Response : %f/%f = %f \n",m,mcm,result);
	
	return &result;
}


//MULTIPLICACION
float *mul_1_svc(inputs *argp, struct svc_req *rqstp){
	static float  result;
	
	//Todo lo necesario para la multiplicacion de fracciones
	float m=argp->num1*argp->num3;				//Calcula el numerador final
	float d=argp->num2*argp->num4;				//Calcula el denominador final

	//Ponemos aqui nuestro codigo para la multiplicion
	result = m/d;
	printf("Got Request : Multiplica %f/%f y %f/%f \n",argp->num1,argp->num2,argp->num3,argp->num4);
	printf("Sent Response : %f/%f = %f \n",m,d,result);
	return &result;
}


//DIVISION
float *div_1_svc(inputs *argp, struct svc_req *rqstp){
	static float  result;
	
	//Todo lo necesario para la division de fracciones
	float m=argp->num1*argp->num4;				//Calcula el numerador final
	float d=argp->num2*argp->num3;				//Calcula el denominador final

	//Ponemos aqui nuestro codigo para la division
	result = m/d;
	printf("Got Request : Divide %f/%f y %f/%f \n",argp->num1,argp->num2,argp->num3,argp->num4);
	printf("Sent Response : %f/%f = %f \n",m,d,result);

	return &result;
}

