/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>
#include <stdio.h>

float
calculadora_prog_1(char *host, float a, float b, char op, CLIENT *clnt)
{
	float  *result_1;
	inputs  add_1_arg;
	float  *result_2;
	inputs  sub_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;
	float  *result_5;
	inputs  res_1_arg;
	float  *result_6;
	inputs  pot_1_arg;


//SUMA
	if (op=='+'){
		add_1_arg.num1=a; 		//El primer sumando va a ser el primer float que pasamos.
		add_1_arg.num2=b; 		//El segundo sumando sera el segundo float.
		add_1_arg.operador=op; 	//El char que pasemos sera el operador de la suma.
		
		result_1 = add_1(&add_1_arg, clnt);		//Calcula la suma
		if(result_1 == (float *) NULL){ 		//Comprueba que se hace bien la suma, si esta vacio el resultado es que no se ha hecho
			clnt_perror(clnt, "SYNTAX ERROR");	//Nos da un mensaje de error
		}
	
		return *result_1; 		//Nos devuelve el resultado de la suma;
	}
	
//RESTA
	if (op=='-'){
		sub_1_arg.num1=a; 		//El minuendo va a ser el primer float que pasamos.
		sub_1_arg.num2=b; 		//El sustraendo sera el segundo float.
		sub_1_arg.operador=op; 	//El char que pasemos sera el operador de la resta.
		
		//Viene por defecto al crearse con rpcgen, lo dejo asi.
		result_2= sub_1(&sub_1_arg, clnt);		//Calcula la resta
		if(result_2 == (float *) NULL){ 		//Comprueba que se hace bien la resta, si esta vacio el resultado es que no se ha hecho
			clnt_perror(clnt, "SYNTAX ERROR");	//Nos da un mensaje de error
		}
	
		return *result_2; 		//Nos devuelve el resultado de la resta;
	}
	
	
//MULTIPLICACION
	if (op =='*'){
		mul_1_arg.num1=a; 		//El primer factor va a ser el primer float que pasamos.
		mul_1_arg.num2=b; 		//El segundo factor sera el segundo float.
		mul_1_arg.operador=op; 	//El char que pasemos sera el operador de la multiplicación.
		
		//Viene por defecto al crearse con rpcgen, lo dejo asi.
		result_3= mul_1(&mul_1_arg, clnt);		//Calcula la multiplicacion
		if(result_3 == (float *) NULL){ 		//Comprueba que se hace bien la multiplicacion, si esta vacio el resultado es que no se ha hecho
			clnt_perror(clnt, "SYNTAX ERROR");	//Nos da un mensaje de error
		}
	
		return *result_3; 		//Nos devuelve el producto de la multiplicacion;
	}
	
//DIVISION
	if (op =='/'){
		div_1_arg.num1=a; 		//El dividendo va a ser el primer float que pasamos.
		div_1_arg.num2=b; 		//El divisor sera el segundo float.
		div_1_arg.operador=op; 	//El char que pasemos sera el operador de la division.
		
		//Tenemos que tener en cuenta que si el divisor es 0 nos tiene que dar error por tanto
		if (b == 0){
			printf("SYNTAX ERROR \n");
			exit(0);
		}else{
		
		//Viene por defecto al crearse con rpcgen, lo dejo asi.
			result_4= div_1(&div_1_arg, clnt);		//Calcula la division
			if(result_4 == (float *) NULL){ 		//Comprueba que se hace bien la division, si esta vacio el resultado es que no se ha hecho
				clnt_perror(clnt, "SYNTAX ERROR");	//Nos da un mensaje de error
			}
	
			return *result_4; 	//Nos devuelve el cociente de la division;
		}
	}
	
//RESTO
	if (op =='r'){
		res_1_arg.num1=a; 		//El dividendo va a ser el primer float que pasamos.
		res_1_arg.num2=b; 		//El divisor sera el segundo float.
		res_1_arg.operador=op; 	//El char que pasemos sera el operador del resto.
		
		//Tenemos que tener en cuenta que si el divisor es 0 nos tiene que dar error por tanto
		if (b == 0){
			printf("SYNTAX ERROR \n");
			exit(0);
		}else{
		
		//Viene por defecto al crearse con rpcgen, lo dejo asi.
			result_5= res_1(&res_1_arg, clnt);		//Calcula la division
			if(result_5 == (float *) NULL){ 		//Comprueba que se hace bien la division, si esta vacio el resultado es que no se ha hecho
				clnt_perror(clnt, "SYNTAX ERROR");	//Nos da un mensaje de error
			}
	
			return *result_5; 	//Nos devuelve el resto de la division;
		}
	}

//POTENCIA
	if (op =='^'){
		pot_1_arg.num1=a; 		//La base va a ser el primer float que pasamos.
		pot_1_arg.num2=b; 		//El exponente sera el segundo float.
		pot_1_arg.operador=op; 	//El char que pasemos sera el operador de la potencia.
		
		//Viene por defecto al crearse con rpcgen, lo dejo asi.
		result_6 = pot_1(&pot_1_arg, clnt);
		if (result_6 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	
		return *result_6; 		//Nos devuelve el resultado de la potencia;
	}


}

int main (int argc, char *argv[]){
	//Añadimos las variables que faltan
	char *host;
	float a, b;
	char op;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	//Creamos un pequeño menu
	printf("Bienvenido estas usando la calculadora de Claudia \n");
	printf("Recuerda: \n + para la SUMA \n - para la RESTA \n * para la multiplicacion \n / para la division \n r para el resto \n ^ para la potencia \n");
	printf("Indique el primer numero \n");
	scanf("%f", &a);
	printf("Indique el segundo numero \n");
	scanf("%f", &b);
	printf("Indique el operador \n");
	scanf("%s", &op);
	
	//Viene por defecto al crearse con rpcgen, lo dejo asi.
	host = argv[1];
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	//Imprimimos el resultado
	printf("El resultado es: %f \n",calculadora_prog_1(host,a,b,op,clnt));
	
	//Viene por defecto al crearse con rpcgen, lo dejo asi.
	clnt_destroy (clnt);
	exit (0);
}
