/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>
#include <stdio.h>

float *
add_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	//Ponemos aqui nuestro codigo para la suma
	result = argp->num1+argp->num2;
	printf("Got Request : Suma %f y %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);

	return &result;
}

float *
sub_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	//Ponemos aqui nuestro codigo para la resta
	result = argp->num1-argp->num2;
	printf("Got Request : Resta %f y %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);


	return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	//Ponemos aqui nuestro codigo para la multiplicacion
	result = argp->num1*argp->num2;
	printf("Got Request : Multiplca %f y %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);

	return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	//Ponemos aqui nuestro codigo para la division
	result = argp->num1/argp->num2;
	printf("Got Request : Divide %f y %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);

	return &result;
}

float *
res_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;
	static int aux;
	static int m;

	//Ponemos aqui nuestro codigo para la division
	aux=argp->num1/argp->num2;
	printf(" %f \n", aux);

	m=argp->num2*aux;
	result=argp->num1-m;
	printf("Got Request : La raiz %f y %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);

	return &result;
}

float *
pot_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	//Ponemos aqui nuestro codigo para la division
	for(int i=0; i<argp->num2; i++)
		result=argp->num1*argp->num1;
	printf("Got Request : Eleva %f a %f \n",argp->num1,argp->num2);
	printf("Sent Response : %f \n", result);

	return &result;
}
